### ISSUE TITLE
Peer-to-Peer Code Review (11/17/2022)

### ISSUE THREAD

**Issue by Htetaungkyaw71** [ernestkorir/Leaderboard#3]
# Acknowledgements

- Good Github flow 👍🏼 
- No linter errors 💯 
- Clean and readable code 🥇 

# Optional
- Kindly create modules folder inside src folder and then add all JavaScript files (not index.js) to this modules folder.

**Comment by V-Blaze** [comment]
Good job following the best coding practices..  

- I think the submit form and error message handler needs slight improvement. Since you are not using the error response from the server, I think you should prevent making an API call when the input fields are empty.

**Comment by ernestkorir** [comment]
thanks for the issues
